### ISSUE TITLE
Beacon Tracking todos

### ISSUE THREAD

**Issue by wescarr** [covidtrace/app#33]
- [x] Associate locations to beacons when submitting report
- [x] Change uuid every hour? when broadcasting
- [ ] Switch clientId if collision is detected
- [x] Automatically start broadcasting beacons instead of manually
- [x] Only show BLE notification when app is not running

**Comment by wescarr** [comment]
No longer relevant since we've switched to the Google/Apple EN API
